ignore-paths:
  - examples
ignore-patterns:
  - (^|/).*run\.py(/|$)
strictness: veryhigh
member-warnings: true
test-warnings: true
pyroma:
  run: true
pyflakes:
  run: false
mccabe:
  run: false
pep8:
  full: true
